name: Build & Release ShieldNet APK 🚀

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Permission
        run: chmod +x ./gradlew

      - name: Clean Project
        run: ./gradlew clean

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Rename APK
        run: mv app/build/outputs/apk/debug/app-debug.apk ShieldNet.apk

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0
          name: ShieldNet Release
          files: ShieldNet.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}